apiVersion: v1
kind: ConfigMap
metadata:
  name: fashionweb-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  DB_HOST: "mysql" # Keeping service name consistent for now
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_DATABASE_NAME: {{ .Values.config.dbName | quote }}
  DB_SSL: {{ .Values.config.dbSsl | quote }}
  BACKEND_PORT: {{ .Values.backend.service.port | quote }}
  ELASTICSEARCH_HOST: {{ .Values.config.elasticsearchHost | quote }}
  ELASTICSEARCH_PORT: {{ .Values.config.elasticsearchPort | quote }}
