apiVersion: v1
kind: Secret
metadata:
  name: fashionweb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secrets.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_ROOT_PASSWORD: {{ .Values.secrets.dbRootPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  EMAIL_APP: {{ .Values.secrets.emailApp | quote }}
  EMAIL_APP_PASSWORD: {{ .Values.secrets.emailAppPassword | quote }}
