apiVersion: v1
kind: Secret
metadata:
  name: fashionweb-secret
  namespace: fashionweb
type: Opaque
stringData:
  DB_USERNAME: "root"
  DB_PASSWORD: "root123"
  DB_ROOT_PASSWORD: "root123"
  JWT_SECRET: "bingo27062000"
  EMAIL_APP: "manhha280699@gmail.com"
  EMAIL_APP_PASSWORD: "your_app_password"
